import sqlalchemy as sa

METADATA = sa.MetaData()

RUNS = sa.Table(
    "runs",
    METADATA,
    sa.Column("run_id", sa.String, primary_key=True),
    sa.Column("env", sa.String, nullable=False),
    sa.Column("strategy", sa.String, nullable=False),
    sa.Column("run_window", sa.String),
    sa.Column("phase", sa.String),
    sa.Column("event_name", sa.String),
    sa.Column("dry_run", sa.Boolean, nullable=False, default=False),
    sa.Column("git_sha", sa.String),
    sa.Column("workflow", sa.String),
    sa.Column("workflow_run_id", sa.String),
    sa.Column("workflow_attempt", sa.Integer),
    sa.Column("config_json", sa.JSON, nullable=False, default=dict),
    sa.Column("status", sa.String, nullable=False, default="STARTED"),
    sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    sa.Column("finished_at", sa.DateTime(timezone=True)),
    sa.Column("notes", sa.Text),
)

UNIVERSE = sa.Table(
    "universe",
    METADATA,
    sa.Column("universe_id", sa.String, primary_key=True),
    sa.Column("env", sa.String, nullable=False),
    sa.Column("strategy", sa.String, nullable=False),
    sa.Column("as_of_date", sa.String, nullable=False),
    sa.Column("source", sa.String, nullable=False),
    sa.Column("params_json", sa.JSON, nullable=False, default=dict),
    sa.Column("payload_json", sa.JSON, nullable=False, default=dict),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
)

UNIVERSE_MEMBERS = sa.Table(
    "universe_members",
    METADATA,
    sa.Column("universe_member_id", sa.String, primary_key=True),
    sa.Column("universe_id", sa.String, sa.ForeignKey("universe.universe_id"), nullable=False),
    sa.Column("code", sa.String, nullable=False),
    sa.Column("market", sa.String),
    sa.Column("weight", sa.Float),
    sa.Column("rank", sa.Integer),
    sa.Column("meta_json", sa.JSON, nullable=False, default=dict),
)

ORDERS = sa.Table(
    "orders",
    METADATA,
    sa.Column("order_id", sa.String, primary_key=True),
    sa.Column("env", sa.String, nullable=False),
    sa.Column("run_id", sa.String, sa.ForeignKey("runs.run_id")),
    sa.Column("strategy", sa.String, nullable=False),
    sa.Column("sid", sa.Integer, nullable=False),
    sa.Column("mode", sa.Integer, nullable=False),
    sa.Column("code", sa.String, nullable=False),
    sa.Column("market", sa.String),
    sa.Column("side", sa.String, nullable=False),
    sa.Column("ord_type", sa.String, nullable=False),
    sa.Column("qty", sa.Integer, nullable=False),
    sa.Column("limit_price", sa.Float),
    sa.Column("stage", sa.String),
    sa.Column("client_order_key", sa.String, nullable=False),
    sa.Column("status", sa.String, nullable=False, default="INTENT"),
    sa.Column("kis_odno", sa.String),
    sa.Column("request_json", sa.JSON, nullable=False, default=dict),
    sa.Column("response_json", sa.JSON),
    sa.Column("submitted_at", sa.DateTime(timezone=True)),
    sa.Column("acked_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    sa.UniqueConstraint("env", "client_order_key", name="uq_orders_env_client_order_key"),
)

FILLS = sa.Table(
    "fills",
    METADATA,
    sa.Column("fill_id", sa.String, primary_key=True),
    sa.Column("env", sa.String, nullable=False),
    sa.Column("run_id", sa.String, sa.ForeignKey("runs.run_id")),
    sa.Column("order_id", sa.String, sa.ForeignKey("orders.order_id")),
    sa.Column("kis_odno", sa.String),
    sa.Column("trade_id", sa.String),
    sa.Column("code", sa.String, nullable=False),
    sa.Column("market", sa.String),
    sa.Column("side", sa.String, nullable=False),
    sa.Column("qty", sa.Integer, nullable=False),
    sa.Column("price", sa.Float, nullable=False),
    sa.Column("fee", sa.Float, nullable=False, default=0.0),
    sa.Column("tax", sa.Float, nullable=False, default=0.0),
    sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("raw_json", sa.JSON, nullable=False, default=dict),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    sa.UniqueConstraint("env", "trade_id", name="uq_fills_env_trade_id"),
    sa.UniqueConstraint(
        "env",
        "kis_odno",
        "code",
        "side",
        "qty",
        "price",
        "filled_at",
        name="uq_fills_fallback",
    ),
)

POSITIONS = sa.Table(
    "positions",
    METADATA,
    sa.Column("position_id", sa.String, primary_key=True),
    sa.Column("env", sa.String, nullable=False),
    sa.Column("strategy", sa.String, nullable=False),
    sa.Column("sid", sa.Integer, nullable=False),
    sa.Column("mode", sa.Integer, nullable=False),
    sa.Column("code", sa.String, nullable=False),
    sa.Column("market", sa.String),
    sa.Column("qty", sa.Integer, nullable=False, default=0),
    sa.Column("avg_buy_price", sa.Float),
    sa.Column("total_cost", sa.Float, nullable=False, default=0.0),
    sa.Column("realized_pnl", sa.Float, nullable=False, default=0.0),
    sa.Column("last_trade_at", sa.DateTime(timezone=True)),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    sa.UniqueConstraint("env", "strategy", "sid", "mode", "code", name="uq_positions_identity"),
)

LEDGER_EVENTS = sa.Table(
    "ledger_events",
    METADATA,
    sa.Column("ledger_event_id", sa.String, primary_key=True),
    sa.Column("env", sa.String, nullable=False),
    sa.Column("run_id", sa.String, sa.ForeignKey("runs.run_id")),
    sa.Column("event_type", sa.String, nullable=False),
    sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("code", sa.String),
    sa.Column("market", sa.String),
    sa.Column("sid", sa.Integer),
    sa.Column("mode", sa.Integer),
    sa.Column("side", sa.String),
    sa.Column("qty", sa.Integer),
    sa.Column("price", sa.Float),
    sa.Column("kis_odno", sa.String),
    sa.Column("client_order_key", sa.String),
    sa.Column("ok", sa.Boolean, nullable=False, default=True),
    sa.Column("reasons", sa.JSON, nullable=False, default=list),
    sa.Column("stage", sa.String),
    sa.Column("payload_json", sa.JSON, nullable=False, default=dict),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
)
