param([string]$Repo="/home/infiny/apps/Jeihyuck-rolling-k-auto-trade-KIS-refacored", [string]$Distro="Ubuntu-22.04")
$ErrorActionPreference="Continue"; $failed=$false; $wsl="$env:SystemRoot\System32\wsl.exe"; $base="$Repo/scripts/wsl"
$expected=[ordered]@{
# Mail/Health arguments remain separate tokens: send-market-log-mail.sh us; check-nullim-day-health.sh kr
"PB1 KR Prep WSL"=@("06:30","run-kr-prep.sh",$false);"PB1 KR AM WSL"=@("08:55","run-kr-am.sh",$true);"PB1 KR Afternoon WSL"=@("13:00","run-kr-afternoon.sh",$true);"PB1 KR Close WSL"=@("15:15","run-kr-close.sh",$true);"PB1 KR Mail WSL"=@("16:00","send-kr-log-mail.sh",$false);"PB1 KR Health WSL"=@("16:10","check-nullim-day-health.sh",$false);
"PB1 US Prep Prewarm EDT WSL"=@("19:30","run-us-prep.sh",$false);"PB1 US Prep Prewarm EST WSL"=@("20:30","run-us-prep.sh",$false);"PB1 US Prep WSL"=@("21:30","run-us-prep.sh",$false);"PB1 US Prep Recovery WSL"=@("22:10","run-us-prep-recovery.sh",$false);"PB1 US AM Preflight WSL"=@("22:20","check-us-prep-before-am.sh",$false);"PB1 US AM WSL"=@("22:30","run-us-am.sh",$true);"PB1 US Afternoon WSL"=@("02:00","run-us-afternoon.sh",$true);"PB1 US Close WSL"=@("05:05","run-us-close.sh",$true);"PB1 US Mail WSL"=@("07:00","send-us-log-mail.sh",$false);"PB1 US Health WSL"=@("07:10","check-nullim-day-health.sh",$false)}
function Get-ActionText($Task) { (@($Task.Actions) | ForEach-Object { "$($_.Execute) $($_.Arguments)" }) -join " " }
foreach($name in $expected.Keys) {
  $info=Get-ScheduledTaskInfo -TaskName $name -ErrorAction SilentlyContinue; $task=Get-ScheduledTask -TaskName $name -TaskPath '\' -ErrorAction SilentlyContinue
  if($null -eq $task){Write-Host "[SCHEDULER][FAIL] task=$name field=Task expected=present actual=missing";$failed=$true;continue}
  $a=Get-ActionText $task; $trigs=@($task.Triggers); $e=$expected[$name]; $requiredArg=if($name -match "KR (Mail|Health)"){"kr"}elseif($name -match "US (Mail|Health)"){"us"}else{$null}
  $checks=[ordered]@{
    TaskPath=@($task.TaskPath -eq '\','\\',$task.TaskPath); State=@($task.State -ne 'Disabled','enabled',$task.State); RepoPath=@($a -match [regex]::Escape($Repo),$Repo,$a); Distro=@($a -match [regex]::Escape($Distro),$Distro,$a); Command=@($a -match [regex]::Escape($e[1]),$e[1],$a); Argument=@($null -eq $requiredArg -or $a -match "(?<![A-Za-z0-9_.-])$requiredArg(?![A-Za-z0-9_.-])",$(if($null -eq $requiredArg){"none"}else{$requiredArg}),$a); UnsetNullimAppDir=@($a -match "unset[ ]+NULLIM_APP_DIR","unset NULLIM_APP_DIR",$a); BashLogin=@($a -match 'bash -lc','bash -lc',$a); TriggerCount=@($trigs.Count -eq 1,1,$trigs.Count); StartBoundary=@($trigs.Count -eq 1 -and $trigs[0].StartBoundary -match "T$([regex]::Escape($e[0])):",$e[0],$(if($trigs.Count){$trigs[0].StartBoundary}else{'none'})); StartWhenAvailable=@($task.Settings.StartWhenAvailable,$true,$task.Settings.StartWhenAvailable); MultipleInstances=@($task.Settings.MultipleInstances -eq 'IgnoreNew','IgnoreNew',$task.Settings.MultipleInstances); WakeToRun=@($task.Settings.WakeToRun,$true,$task.Settings.WakeToRun); RunOnlyIfIdle=@(-not $task.Settings.RunOnlyIfIdle,$false,$task.Settings.RunOnlyIfIdle); DisallowStartIfOnBatteries=@(-not $task.Settings.DisallowStartIfOnBatteries,$false,$task.Settings.DisallowStartIfOnBatteries); StopIfGoingOnBatteries=@(-not $task.Settings.StopIfGoingOnBatteries,$false,$task.Settings.StopIfGoingOnBatteries); RestartCount=@((!$e[2] -or $null -eq $task.Settings.RestartCount -or [int]$task.Settings.RestartCount -eq 0),'null_or_0',$task.Settings.RestartCount) }
  foreach($field in $checks.Keys){$c=$checks[$field];if(!$c[0]){Write-Host "[SCHEDULER][FAIL] task=$name field=$field expected=$($c[1]) actual=$($c[2]) NextRunTime=$($info.NextRunTime) LastTaskResult=$($info.LastTaskResult)";$failed=$true}}
}
$canonical=@($expected.Keys);$repoMarker='Jeihyuck-rolling-k-auto-trade-KIS-refacored';$runnerMarker='run-kr-|run-us-|run_pb1_kr\.sh|send-(market|kr|us)-log-mail\.sh|check-nullim-day-health\.sh|pb1_runner|trade_session_runner';$non=0
Get-ScheduledTask|ForEach-Object{$a=Get-ActionText $_;$isNullimTask=$a -match [regex]::Escape($repoMarker) -and $a -match $runnerMarker;if(($canonical -notcontains $_.TaskName -or $_.TaskPath -ne '\') -and $isNullimTask){Write-Host "[SCHEDULER][FAIL] reason=NON_CANONICAL_WINDOWS_TASK task=$($_.TaskName)";$non++;$failed=$true}}
& $wsl -d $Distro -- bash -lc "cd '$Repo' && bash scripts/wsl/verify-no-nullim-auto-scheduler.sh";if($LASTEXITCODE -ne 0){$failed=$true;Write-Host '[SCHEDULER_POLICY][FAIL] reason=FORBIDDEN_WSL_SCHEDULER'}
if($failed){exit 1};Write-Host '[SCHEDULER_POLICY][OK]';Write-Host 'owner=WINDOWS_TASK_SCHEDULER';Write-Host 'canonical_windows_tasks=16';Write-Host "noncanonical_windows_tasks=$non";Write-Host 'forbidden_wsl_sources=0'
