# -*- coding: utf-8 -*-
"""공용 상수 및 설정 래퍼.

core 모듈을 여러 파일로 분리하면서도 기존 전역 상수 참조 방식은 그대로
유지할 수 있도록 config 값들을 한 곳에 모았다.
"""
from __future__ import annotations

from . import config

logger = config.logger
_cfg = config._cfg
LOG_DIR = config.LOG_DIR
STATE_FILE = config.STATE_FILE
MARKET_MAP = config.MARKET_MAP
EXCLUDE_STATE = config.EXCLUDE_STATE
KST = config.KST
SELL_FORCE_TIME_STR = config.SELL_FORCE_TIME_STR
SELL_FORCE_TIME = config.SELL_FORCE_TIME
SELL_ALL_BALANCES_AT_CUTOFF = config.SELL_ALL_BALANCES_AT_CUTOFF
RATE_SLEEP_SEC = config.RATE_SLEEP_SEC
FORCE_SELL_PASSES_CUTOFF = config.FORCE_SELL_PASSES_CUTOFF
FORCE_SELL_PASSES_CLOSE = config.FORCE_SELL_PASSES_CLOSE
PARTIAL1 = config.PARTIAL1
PARTIAL2 = config.PARTIAL2
TRAIL_PCT = config.TRAIL_PCT
FAST_STOP = config.FAST_STOP
ATR_STOP = config.ATR_STOP
TIME_STOP_TIME = config.TIME_STOP_TIME
DEFAULT_PROFIT_PCT = config.DEFAULT_PROFIT_PCT
DEFAULT_LOSS_PCT = config.DEFAULT_LOSS_PCT
DAILY_CAPITAL = config.DAILY_CAPITAL
CAP_CAP = config.CAP_CAP
SLIPPAGE_LIMIT_PCT = config.SLIPPAGE_LIMIT_PCT
SLIPPAGE_ENTER_GUARD_PCT = config.SLIPPAGE_ENTER_GUARD_PCT
VWAP_TOL = config.VWAP_TOL
W_MAX_ONE = config.W_MAX_ONE
W_MIN_ONE = config.W_MIN_ONE
REBALANCE_ANCHOR = config.REBALANCE_ANCHOR
WEEKLY_ANCHOR_REF = config.WEEKLY_ANCHOR_REF
MOMENTUM_OVERRIDES_FORCE_SELL = config.MOMENTUM_OVERRIDES_FORCE_SELL
MOM_FAST = config.MOM_FAST
MOM_SLOW = config.MOM_SLOW
MOM_TH_PCT = config.MOM_TH_PCT
USE_PULLBACK_ENTRY = config.USE_PULLBACK_ENTRY
PULLBACK_LOOKBACK = config.PULLBACK_LOOKBACK
PULLBACK_DAYS = config.PULLBACK_DAYS
PULLBACK_REVERSAL_BUFFER_PCT = config.PULLBACK_REVERSAL_BUFFER_PCT
PULLBACK_TOPN = config.PULLBACK_TOPN
PULLBACK_UNIT_WEIGHT = config.PULLBACK_UNIT_WEIGHT
CHAMPION_MIN_TRADES = config.CHAMPION_MIN_TRADES
CHAMPION_MIN_WINRATE = config.CHAMPION_MIN_WINRATE
CHAMPION_MAX_MDD = config.CHAMPION_MAX_MDD
CHAMPION_MIN_SHARPE = config.CHAMPION_MIN_SHARPE
CHAMPION_A_RULES = config.CHAMPION_A_RULES
GOOD_ENTRY_PULLBACK_RANGE = config.GOOD_ENTRY_PULLBACK_RANGE
GOOD_ENTRY_MA20_RANGE = config.GOOD_ENTRY_MA20_RANGE
GOOD_ENTRY_MAX_FROM_PEAK = config.GOOD_ENTRY_MAX_FROM_PEAK
GOOD_ENTRY_MIN_RR = config.GOOD_ENTRY_MIN_RR
GOOD_ENTRY_MIN_INTRADAY_SIG = config.GOOD_ENTRY_MIN_INTRADAY_SIG
BAD_ENTRY_MAX_MA20_DIST = config.BAD_ENTRY_MAX_MA20_DIST
BAD_ENTRY_MAX_PULLBACK = config.BAD_ENTRY_MAX_PULLBACK
BAD_ENTRY_MAX_BELOW_VWAP_RATIO = config.BAD_ENTRY_MAX_BELOW_VWAP_RATIO
NEUTRAL_ENTRY_SCALE = config.NEUTRAL_ENTRY_SCALE
ALLOW_WHEN_CLOSED = config.ALLOW_WHEN_CLOSED
STATE_WEEKLY_PATH = config.STATE_WEEKLY_PATH
_this_iso_week_key = config._this_iso_week_key

__all__ = [
    "logger",
    "_cfg",
    "LOG_DIR",
    "STATE_FILE",
    "MARKET_MAP",
    "EXCLUDE_STATE",
    "KST",
    "SELL_FORCE_TIME_STR",
    "SELL_FORCE_TIME",
    "SELL_ALL_BALANCES_AT_CUTOFF",
    "RATE_SLEEP_SEC",
    "FORCE_SELL_PASSES_CUTOFF",
    "FORCE_SELL_PASSES_CLOSE",
    "PARTIAL1",
    "PARTIAL2",
    "TRAIL_PCT",
    "FAST_STOP",
    "ATR_STOP",
    "TIME_STOP_TIME",
    "DEFAULT_PROFIT_PCT",
    "DEFAULT_LOSS_PCT",
    "DAILY_CAPITAL",
    "CAP_CAP",
    "SLIPPAGE_LIMIT_PCT",
    "SLIPPAGE_ENTER_GUARD_PCT",
    "VWAP_TOL",
    "W_MAX_ONE",
    "W_MIN_ONE",
    "REBALANCE_ANCHOR",
    "WEEKLY_ANCHOR_REF",
    "MOMENTUM_OVERRIDES_FORCE_SELL",
    "MOM_FAST",
    "MOM_SLOW",
    "MOM_TH_PCT",
    "USE_PULLBACK_ENTRY",
    "PULLBACK_LOOKBACK",
    "PULLBACK_DAYS",
    "PULLBACK_REVERSAL_BUFFER_PCT",
    "PULLBACK_TOPN",
    "PULLBACK_UNIT_WEIGHT",
    "CHAMPION_MIN_TRADES",
    "CHAMPION_MIN_WINRATE",
    "CHAMPION_MAX_MDD",
    "CHAMPION_MIN_SHARPE",
    "CHAMPION_A_RULES",
    "GOOD_ENTRY_PULLBACK_RANGE",
    "GOOD_ENTRY_MA20_RANGE",
    "GOOD_ENTRY_MAX_FROM_PEAK",
    "GOOD_ENTRY_MIN_RR",
    "GOOD_ENTRY_MIN_INTRADAY_SIG",
    "BAD_ENTRY_MAX_MA20_DIST",
    "BAD_ENTRY_MAX_PULLBACK",
    "BAD_ENTRY_MAX_BELOW_VWAP_RATIO",
    "NEUTRAL_ENTRY_SCALE",
    "ALLOW_WHEN_CLOSED",
    "STATE_WEEKLY_PATH",
    "_this_iso_week_key",
]

