from __future__ import annotations


class ReasonCode:
    ENTRY_BREAKOUT = "ENTRY_BREAKOUT"
    ENTRY_PULLBACK = "ENTRY_PULLBACK"
    ENTRY_VCP = "ENTRY_VCP"
    ENTRY_PYRAMID = "ENTRY_PYRAMID"

    EXIT_STOP_LOSS = "EXIT_STOP_LOSS"
    EXIT_TRAIL = "EXIT_TRAIL"
    EXIT_TP_PARTIAL = "EXIT_TP_PARTIAL"
    EXIT_TIME = "EXIT_TIME"
    EXIT_REGIME = "EXIT_REGIME"
    EXIT_RISK_BUDGET = "EXIT_RISK_BUDGET"

    SKIP_NO_CANDIDATES = "SKIP_NO_CANDIDATES"
    SKIP_DEGRADED_TIME = "SKIP_DEGRADED_TIME"
