name: Daily Reports (after close)

on:
  push:
    branches: [ feature/rkmax, feature/rkmax-v2 ]
  pull_request:
    branches: [ feature/rkmax, feature/rkmax-v2 ]
  schedule:
    # 장 마감 이후 KST 15:40 (UTC 06:40, 월~금)
    - cron: "40 6 * * 1-5"
  workflow_dispatch:

concurrency:
  group: daily-reports
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      # ===== Secrets =====
      KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}
      KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}
      CANO: ${{ secrets.CANO }}
      ACNT_PRDT_CD: ${{ secrets.ACNT_PRDT_CD }}
      KIS_ENV: ${{ secrets.KIS_ENV }}

      # 리포트 표기용 파라미터
      PARTIAL1: "0.5"
      PARTIAL2: "0.3"
      TRAIL_PCT: "0.02"
      FAST_STOP: "0.01"
      ATR_STOP: "1.5"
      TIME_STOP_HHMM: "13:00"
      SELL_FORCE_TIME: "14:30"
      DAILY_CAPITAL: "10000000"
      SLIPPAGE_ENTER_GUARD_PCT: "1.5"
      TOP_K: "10"
      LOOKBACK_DAYS: "10"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pandas numpy

      - name: Generate CEO report (daily/weekly/monthly)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -euxo pipefail
          python -m trader.report_ceo

      - name: Upload CEO report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ceo-report
          path: trader/reports/
          if-no-files-found: warn
          retention-days: 30

      - name: Upload rebalance artifacts (if any from earlier)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rebalance-results
          path: rebalance_results/*.json
          if-no-files-found: warn
          retention-days: 60

      - name: Upload trade logs (redundant safety)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trade-logs
          path: trader/logs/*.json
          if-no-files-found: ignore
          retention-days: 14
