name: Rebalance Snapshot (08:50 KST)

on:
  push:
    branches: [ feature/rkmax, feature/rkmax-v2 ]
  pull_request:
    branches: [ feature/rkmax, feature/rkmax-v2 ]
  schedule:
    # 매 영업일 KST 08:50 (UTC 23:50, 일~목)
    - cron: "50 23 * * 0-4"
  workflow_dispatch:

concurrency:
  group: rebalance-snapshot
  cancel-in-progress: true

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      # ===== Secrets =====
      KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}
      KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}
      CANO: ${{ secrets.CANO }}
      ACNT_PRDT_CD: ${{ secrets.ACNT_PRDT_CD }}
      KIS_ENV: ${{ secrets.KIS_ENV }}

      # ===== 전략/운영 파라미터 =====
      TOP_K: "10"
      LOOKBACK_DAYS: "10"
      REBALANCE_ANCHOR: "today"
      REBALANCE_SNAPSHOT_TIME_KST: "08:50"
      DAILY_CAPITAL: "10000000"
      ORDER_THROTTLE_SEC: "0.3"
      REBALANCE_OUT_DIR: "rebalance_results"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # ensure api server deps exist
          pip install fastapi uvicorn

      - name: Run FastAPI (bg) with healthcheck
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -euxo pipefail
          nohup uvicorn rolling_k_auto_trade_api.main:app --host 127.0.0.1 --port 8000 > fastapi.log 2>&1 &
          SV_PID=$!
          for i in {1..90}; do
            if curl -sSf http://127.0.0.1:8000/docs >/dev/null; then
              echo "API UP after $i sec"
              break
            fi
            if ! ps -p "$SV_PID" >/dev/null; then
              echo "Uvicorn crashed early. ---- fastapi.log ----"
              cat fastapi.log || true
              exit 1
            fi
            sleep 1
          done

      - name: Make output dir
        run: mkdir -p rebalance_results

      - name: Call Rebalance API (08:50 snapshot)
        run: |
          set -euxo pipefail
          KST_DATE=$(TZ=Asia/Seoul date +%F)
          OUT="rebalance_results/rebalance_${KST_DATE}_0850.json"
          curl --retry 12 --retry-delay 5 --retry-connrefused -sS -X POST "http://127.0.0.1:8000/rebalance/run/${KST_DATE}?force_order=true" -o "${OUT}"
          echo "Saved -> ${OUT}"
          test -s "${OUT}"

      - name: Upload rebalance artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rebalance-results
          path: rebalance_results/*.json
          if-no-files-found: warn
          retention-days: 60

      - name: FastAPI log (cat)
        if: always()
        run: |
          echo "::group::FastAPI Server Log"
          cat fastapi.log || true
          echo "::endgroup::"

      - name: Upload fastapi.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-log
          path: fastapi.log
          if-no-files-found: ignore
          retention-days: 14
